<nav aria-label='breadcrumb'>
    <ol class='breadcrumb hidden-xs hidden-sm'>
        Você está em:
        <li class='breadcrumb-item active ml-1'>
            <a alt='Página inicial' title='Página inicial' href='<?php echo $this->link(array('controller' => 'dashboard'));?>'>
                <i class='fa fa-home'><span class='sr-only'>Página inicial</span></i>
            </a>
        </li>
    </ol>
</nav>

<?php echo $sessionReturn; ?>

<!-- Page Heading -->
<div class='d-sm-flex align-items-center justify-content-between mb-4'>
    <h1 class='h4 mb-0 text-gray-800'>Página inicial</h1>
</div>

<!-- Content Row -->
<div class='row'>

    <div class='col-xl-6 col-sm-12 mb-4'>
        <div class='card border-left-success shadow h-100 py-2'>
            <div class='card-body'>
                <div class='row no-gutters align-items-center'>
                    <div class='col mr-2'>
                        <div class='text-xs font-weight-bold text-success text-uppercase mb-1'>Número de usuários cadastrados</div>
                        <div class='h5 mb-0 font-weight-bold text-gray-800'><?php echo $countUsers; ?></div>
                    </div>
                    <div class='col-auto'>
                        <i class='fas fa-user fa-2x text-gray-300'></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class='col-xl-6 col-sm-12 mb-4'>
        <div class='card border-left-info shadow h-100 py-2'>
            <div class='card-body'>
                <div class='row no-gutters align-items-center'>
                    <div class='col mr-2'>
                        <div class='text-xs font-weight-bold text-info text-uppercase mb-1'>Número de contatos cadastrados</div>
                        <div class='h5 mb-0 font-weight-bold text-gray-800'><?php echo $countContacts; ?></div>
                    </div>
                    <div class='col-auto'>
                        <i class='fas fa-address-card fa-2x text-gray-300'></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class='row'>
    <div class='col-lg-6'>
        <div class='card shadow mb-4'>
            <div class='card-header py-3'>
                <h6 class='m-0 font-weight-bold text-dark'>Últimos usuários cadastrados</h6>
            </div>
            <div class='card-body table-responsive'>
            <?php if (!empty($users)) { ?>
                <div class='table-responsive'>
                    <table class='table table-striped table-hover'>
                        <caption>Lista de usuários</caption>
                        <thead>
                            <tr>
                                <th width='80'>Opções</th>
                                <th>Nome</th>
                                <th>Email</th>
                                <th>Status</th>
                                <th>Criado em</th>
                                <th>Última atualização</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($users as $user) { ?>
                            <tr>
                                <td>
                                <div class='btn-group'>
                                    <a class='btn btn-warning btn-sm' alt='Editar usuário' title='Editar usuário' href='<?php echo $this->link(array('controller' => 'users', 'action' => 'user', 'params' => array('id' => $user->id)));?>'>
                                        <i class='far fa-fw fa-edit fa-lg'></i><span class='sr-only'>Editar usuário</span>
                                    </a>
                                    <a class='btn btn-danger btn-sm removeUser' alt='Remover usuário' title='Remover usuário' href='<?php echo $this->link(array('controller' => 'users', 'action' => 'delete', 'params' => array('id' => $user->id)));?>'>
                                        <i class='fas fa-fw fa-times fa-lg'></i><span class='sr-only'>Remover usuário</span>
                                    </a>
                                </div>
                                </td>
                                <td><?php echo $user->name;?></td>
                                <td><?php echo $user->email;?></td>
                                <td><?php echo $status[$user->status]; ?></td>
                                <td><?php echo $user->created; ?></td>
                                <td><?php echo (empty($user->modified) ? 'Nunca atualizado' : $user->modified); ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            <?php } else { ?>
                <p class='bg-danger p-3 text-white'><?php echo $error_msg_users; ?></p>
            <?php } ?>
            </div>
        </div>
    </div>
    <div class='col-lg-6'>
        <div class='card shadow mb-4'>
            <div class='card-header py-3'>
                <h6 class='m-0 font-weight-bold text-dark'>Últimos contatos cadastrados</h6>
            </div>
            <div class='card-body'>
            <?php if (!empty($contacts)) { ?>
                <div class='table-responsive'>
                    <table class='table table-striped table-hover'>
                        <caption>Lista de contatos</caption>
                        <thead>
                            <tr>
                                <th width='80'>Opções</th>
                                <th>Nome</th>
                                <th>Email</th>
                                <th>Criado em</th>
                                <th>Última atualização</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($contacts as $contact) { ?>
                            <tr>
                                <td>
                                <div class='btn-group'>
                                    <a class='btn btn-warning btn-sm' alt='Editar contato' title='Editar contato' href='<?php echo $this->link(array('controller' => 'contacts', 'action' => 'contact', 'params' => array('id' => $contact->id)));?>'>
                                        <i class='far fa-fw fa-edit fa-lg'></i><span class='sr-only'>Editar contato</span>
                                    </a>
                                    <a class='btn btn-danger btn-sm removeContact' alt='Remover contato' title='Remover contato' href='<?php echo $this->link(array('controller' => 'contacts', 'action' => 'delete', 'params' => array('id' => $contact->id)));?>'>
                                        <i class='fas fa-fw fa-times fa-lg'></i><span class='sr-only'>Remover contato</span>
                                    </a>
                                </div>
                                </td>
                                <td><?php echo $contact->name;?></td>
                                <td><?php echo $contact->email;?></td>
                                <td><?php echo $contact->created; ?></td>
                                <td><?php echo (empty($contact->modified) ? 'Nunca atualizado' : $contact->modified); ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            <?php } else { ?>
                <p class='bg-danger p-3 text-white'><?php echo $error_msg_contacts; ?></p>
            <?php } ?>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $(document).on('click', '.btn.removeUser', function(e){
        e.preventDefault();

        var url = $(this).attr('href'),
            id = $(this).data('id');

        if (confirm('Você deseja mesmo apagar este usuário?')) {
            $.post(url, {id:id}, function(response) {
                if (response.success == 'false') {
                    alert(response.return);
                } else {
                    location.reload();
                }
            }, 'json');
        }
    });

    $(document).on('click', '.btn.removeContact', function(e){
        e.preventDefault();

        var url = $(this).attr('href'),
            id = $(this).data('id');

        if (confirm('Você deseja mesmo apagar este contato?')) {
            $.post(url, {id:id}, function(response) {
                if (response.success == 'false') {
                    alert(response.return);
                } else {
                    location.reload();
                }
            }, 'json');
        }
    });
});
</script>