<nav aria-label='breadcrumb'>
    <ol class='breadcrumb hidden-xs hidden-sm'>
        Você está em:
        <li class='breadcrumb-item ml-1'>
            <a alt='Página inicial' title='Página inicial' href='<?php echo $this->link(array('controller' => 'dashboard'));?>'>
                <i class='fa fa-home'><span class='sr-only'>Página inicial</span></i>
            </a>
        </li>
        <li class='breadcrumb-item active'>
            <a href='<?php echo $this->link(array('controller' => 'contacts'));?>'>
                Lista de contatos
            </a>
        </li>
    </ol>
</nav>

<?php echo $sessionReturn; ?>

<!-- Page Heading -->
<div class='d-sm-flex align-items-center justify-content-between mb-4'>
    <h1 class='h4 mb-0 text-gray-800'>Lista de contatos</h1>
</div>

<div class='row'>
    <div class='col-sm-12'>
        <a class='btn btn-success mb-4 justify-content-end' href='<?php echo $this->link(array('controller' => 'contacts', 'action' => 'contact'));?>'>
            <i class='fas fa-fw fa-plus'></i> Novo contato
        </a>
    </div>
    <div class='col-sm-12'>
        <div class='card shadow mb-4'>
            <div class='card-header py-3'>
                <h6 class='m-0 font-weight-bold text-dark'>Filtro de contatos</h6>
            </div>
            <div class='card-body'>
                <form id='filtros' name='filtros' method='get' action='<?php echo $this->link(array('controller' => 'contacts')); ?>' class='form-row' role='form'>
                    <div class='col-lg-6 mb-2'>
                        <label class='sr-only' for='name'>Nome do contato</label>
                        <input name='name' id='name' type='text' class='form-control' value='<?php echo $get_fields['name']; ?>' placeholder='Nome do contato' />
                    </div>
                    <div class='col-lg'>
                        <input value='Filtrar' class='btn btn-outline-dark' type='submit' />
                        <a class='btn btn-outline-dark' href='<?php echo $this->link(array('controller' => 'contacts'));?>' alt='Limpar filtros' title='Limpar filtros'>
                            <i class='fas fa-fw fa-eraser fa-lg'></i><span class='sr-only'>Limpar filtros</span>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class='row'>
    <div class='col-sm-12'>
        <div class='card shadow mb-4'>
            <div class='card-body pb-0'>
            <?php if (!empty($contacts)) { ?>
                <div class='table-responsive'>
                    <table class='table table-striped table-hover'>
                        <caption>Lista de contatos</caption>
                        <thead>
                            <tr>
                                <th width='80'>Opções</th>
                                <th>Nome</th>
                                <th>Email</th>
                                <th>Criado em</th>
                                <th>Última atualização</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($contacts as $contact) { ?>
                            <tr>
                                <td>
                                <div class='btn-group'>
                                    <a class='btn btn-warning btn-sm' alt='Editar contato' title='Editar contato' href='<?php echo $this->link(array('controller' => 'contacts', 'action' => 'contact', 'params' => array('id' => $contact->id)));?>'>
                                        <i class='far fa-fw fa-edit fa-lg'></i><span class='sr-only'>Editar contato</span>
                                    </a>
                                    <a class='btn btn-danger btn-sm removeContact' alt='Remover contato' title='Remover contato' href='<?php echo $this->link(array('controller' => 'contacts', 'action' => 'delete', 'params' => array('id' => $contact->id)));?>'>
                                        <i class='fas fa-fw fa-times fa-lg'></i><span class='sr-only'>Remover contato</span>
                                    </a>
                                </div>
                                </td>
                                <td><?php echo $contact->name;?></td>
                                <td><?php echo $contact->email;?></td>
                                <td><?php echo $contact->created; ?></td>
                                <td><?php echo (empty($contact->modified) ? 'Nunca atualizado' : $contact->modified); ?></td>
                            </tr>
                        <?php } ?>
                        </tbody>
                    </table>
                </div>
            <?php } else { ?>
                <p class='bg-danger p-3 text-white'><?php echo $error_msg; ?></p>
            <?php } ?>
            <?php if (!empty($pagination)) { ?>
                <nav aria-label='Páginação da lista de contatos'>
                    <?php echo $pagination;?>
                </nav>
            <?php } ?>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $(document).on('click', '.btn.removeContact', function(e){
        e.preventDefault();

        var url = $(this).attr('href'),
            id = $(this).data('id');

        if (confirm('Você deseja mesmo apagar este contato?')) {
            $.post(url, {id:id}, function(response) {
                if (response.success == 'false') {
                    alert(response.return);
                } else {
                    location.reload();
                }
            }, 'json');
        }
    });
});
</script>