		<div class='p-5'>
			<div class='text-center'>
				<h1 class='h4 text-gray-900 mb-4'>Agenda Biofarm - Entrar</h1>
			</div>
			<?php echo $sessionReturn;?>
			<form  method='post' class='user'>
				<div class='form-group'>
					<input type='email' class='form-control form-control-user' id='email' name='email' placeholder='Email' required='required' />
				</div>
				<div class='form-group'>
					<input type='password' class='form-control form-control-user' id='password' name='password' placeholder='Senha' required='required' />
				</div>
				<input type='submit' name='Entrar' id='Entrar' class='btn btn-success btn-user btn-block' value='Entrar' />
			</form>
		</div>