<!DOCTYPE html>
<html lang='pt-br'>
	<head>
        <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
		<meta charset='utf-8' />
		<meta http-equiv='X-UA-Compatible' content='IE=edge' />
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no' />

        <title>Biofarm - Agenda de Contatos - <?php echo (isset($titlePage) && !empty($titlePage) ? $titlePage : 'Biofarm Tecnologia'); ?></title>

		<link rel='icon' href='<?php echo $this->link('/pictures/favicon-biofarm.jpg');?>' type='image/jpg' />

		<!-- Custom fonts for this template-->
		<link href='<?php echo $this->link('/startbootstrap/vendor/fontawesome-free/css/all.min.css');?>' rel='stylesheet' type='text/css' />
		<link href='https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i' rel='stylesheet' />
  
		<!-- Custom styles for this template-->
		<link href='<?php echo $this->link('/startbootstrap/css/sb-admin-2.min.css');?>' rel='stylesheet' />
        <style>
			.xdebug-var-dump:first-child { margin-top:70px; }
			.sidebar .sidebar-brand {
				padding: 0.5rem 1rem;
			}
			.sidebar .sidebar-brand img {
				width: auto;
				max-width: 100%;
				height: auto;
				max-height: 100%;
			}
            .bg-green-biofarm {
                background-color: #1A5632;
            }
		</style>
        <!-- jQuery -->
		<script src='<?php echo $this->link('/startbootstrap/vendor/jquery/jquery.min.js');?>'></script>
        <!-- Moment -->
        <script src='<?php echo $this->link('/vendors/moment/min/moment.min.js');?>'></script>
	</head>
	<body role='document' id='page-top'>
		<!-- Page Wrapper -->
		<div id='wrapper'>

			<!-- Sidebar -->
			<ul class='navbar-nav bg-green-biofarm sidebar sidebar-dark accordion' id='accordionSidebar'>

				<!-- Sidebar - Brand -->
				<a class='sidebar-brand d-flex align-items-center justify-content-center' href='<?php echo $this->link('/');?>'>					
					<img src='<?php echo $this->link('/pictures/logo_white.png');?>' alt='Logo Biofarm' title='Logo Biofarm' />
				</a>

				<!-- Divider -->
				<hr class='sidebar-divider my-0'>

				<!-- Nav Item - Dashboard -->
				<li class='nav-item'>
					<a class='nav-link' href='<?php echo $this->link('/');?>'>
						<i class='fas fa-fw fa-tachometer-alt'></i>
						<span>Dashboard</span>
					</a>
				</li>

				<!-- Divider -->
				<hr class='sidebar-divider' />

				<!-- Heading -->
				<div class='sidebar-heading'>Usuários</div>

				<!-- Nav Item - Pages Collapse Menu -->
				<li class='nav-item'>
					<a class='nav-link collapsed' href='#' data-toggle='collapse' data-target='#collapseUsers' aria-expanded='true' aria-controls='collapseUsers'>
						<i class='fas fa-fw fa-user'></i>
						<span>Usuários</span>
					</a>
					<div id='collapseUsers' class='collapse' aria-labelledby='headingTwo' data-parent='#accordionSidebar'>
						<div class='bg-white py-2 collapse-inner rounded'>
							<a class='collapse-item' href='<?php echo $this->link(array('controller' => 'users')); ?>'>Lista de usuários</a>
							<a class='collapse-item' href='<?php echo $this->link(array('controller' => 'users', 'action' => 'user')); ?>'>Adicionar usuário</a>
						</div>
					</div>
				</li>

				<!-- Divider -->
				<hr class='sidebar-divider' />

				<!-- Heading -->
				<div class='sidebar-heading'>Contatos</div>

				<!-- Nav Item - Pages Collapse Menu -->
				<li class='nav-item'>
					<a class='nav-link collapsed' href='#' data-toggle='collapse' data-target='#collapseContacts' aria-expanded='true' aria-controls='collapseContacts'>
						<i class='fas fa-fw fa-address-card'></i>
						<span>Contatos</span>
					</a>
					<div id='collapseContacts' class='collapse' aria-labelledby='headingTwo' data-parent='#accordionSidebar'>
						<div class='bg-white py-2 collapse-inner rounded'>
							<a class='collapse-item' href='<?php echo $this->link(array('controller' => 'contacts')); ?>'>Lista de contatos</a>
							<a class='collapse-item' href='<?php echo $this->link(array('controller' => 'contacts', 'action' => 'contact')); ?>'>Adicionar contato</a>
						</div>
					</div>
				</li>

				<!-- Divider -->
				<hr class='sidebar-divider d-none d-md-block' />

				<!-- Sidebar Toggler (Sidebar) -->
				<div class='text-center d-none d-md-inline'>
					<button class='rounded-circle border-0' id='sidebarToggle'></button>
				</div>

			</ul>
			<!-- End of Sidebar -->

			<!-- Content Wrapper -->
			<div id='content-wrapper' class='d-flex flex-column'>

				<!-- Main Content -->
				<div id='content'>

					<!-- Topbar -->
					<nav class='navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow'>

						<!-- Sidebar Toggle (Topbar) -->
						<button id='sidebarToggleTop' class='btn btn-link d-md-none rounded-circle mr-3'>
							<i class='fa fa-bars'></i>
						</button>

						<!-- Topbar Navbar -->
						<ul class='navbar-nav ml-auto'>

							<div class='topbar-divider d-none d-sm-block'></div>

							<!-- Nav Item - User Information -->
							<li class='nav-item dropdown no-arrow'>
								<a class='nav-link dropdown-toggle' href='#' id='userDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
									<span class='mr-2 d-none d-lg-inline text-gray-600 small'><?php echo $logged->name; ?></span>
									<img class='img-profile rounded-circle' src='<?php echo $this->link($logged->picture); ?>' />
								</a>
								<!-- Dropdown - User Information -->
								<div class='dropdown-menu dropdown-menu-right shadow animated--grow-in' aria-labelledby='userDropdown'>
									<a class='dropdown-item' href='<?php echo $this->link(array('controller' => 'users', 'action' => 'profile'));?>'>
										<i class='fas fa-user fa-sm fa-fw mr-2 text-gray-400'></i>
										Meu perfil
									</a>
									<div class='dropdown-divider'></div>
									<a class='dropdown-item' href='#' data-toggle='modal' data-target='#logoutModal'>
										<i class='fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400'></i>
										Sair
									</a>
								</div>
							</li>

						</ul>

					</nav>
					<!-- End of Topbar -->

					<!-- Begin Page Content -->
					<div class='container-fluid'>

						<?php echo $viewContent; ?>

					</div>
					<!-- /.container-fluid -->

				</div>
				<!-- End of Main Content -->

				<!-- Footer -->
				<footer class='sticky-footer bg-white'>
					<div class='container my-auto'>
						<div class='copyright text-center my-auto'>
							<span>Copyright &copy; Bruno Betioli 2021</span>
						</div>
					</div>
				</footer>
				<!-- End of Footer -->

			</div>
			<!-- End of Content Wrapper -->
			
		</div>

		<!-- Scroll to Top Button-->
		<a class='scroll-to-top rounded' href='#page-top'>
			<i class='fas fa-angle-up'></i>
		</a>

		<!-- Logout Modal-->
		<div class='modal fade' id='logoutModal' tabindex='-1' role='dialog' aria-labelledby='logoutModalLabel' aria-hidden='true'>
			<div class='modal-dialog' role='document'>
				<div class='modal-content'>
					<div class='modal-header'>
						<h5 class='modal-title' id='logoutModalLabel'>Tem certeza que deseja sair?</h5>
						<button class='close' type='button' data-dismiss='modal' aria-label='Close'>
							<span aria-hidden='true'>×</span>
						</button>
					</div>
					<div class='modal-body'>Clique em sair para encerrar a sessão com o seu usuário ou cancelar para continuar na Agenda de Contatos Biofarm.</div>
					<div class='modal-footer'>
						<button class='btn btn-secondary' type='button' data-dismiss='modal'>Cancelar</button>
						<a class='btn btn-success' href='<?php echo $this->link(array('controller' => 'users', 'action' => 'logout')); ?>'>Sair</a>
					</div>
				</div>
			</div>
		</div>

		<!-- Bootstrap core JavaScript-->
		<script src='<?php echo $this->link('/startbootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js');?>'></script>

		<!-- Core plugin JavaScript-->
		<script src='<?php echo $this->link('/startbootstrap/vendor/jquery-easing/jquery.easing.min.js');?>'></script>

		<!-- Custom scripts for all pages-->
		<script src='<?php echo $this->link('/startbootstrap/js/sb-admin-2.min.js');?>'></script>
    </body>
</html>