<!DOCTYPE html>
<html lang='pt-br'>
    <head>
        <meta charset='utf-8' />
        <meta http-equiv='X-UA-Compatible' content='IE=edge' />
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>

        <title>Biofarm - Agenda de Contatos - <?php echo (isset($titlePage) && !empty($titlePage) ? $titlePage : 'Biofarm Tecnologia'); ?></title>

        <link rel='icon' href='<?php echo $this->link('/pictures/favicon-biofarm.jpg');?>' type='image/jpg' />

        <!-- Custom fonts for this template-->
        <link href='<?php echo $this->link('/startbootstrap/vendor/fontawesome-free/css/all.min.css');?>' rel='stylesheet' type='text/css' />
        <link href='https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i' rel='stylesheet'>

        <!-- Custom styles for this template-->
        <link href='<?php echo $this->link('/startbootstrap/css/sb-admin-2.min.css');?>' rel='stylesheet' />
        <style>
            .xdebug-var-dump:first-child { margin-top:70px; }
            .bg-login-image {
                background: url(<?php echo $this->link('/pictures/biofarm-logo.png');?>);
                background-position: center;
                background-size: cover;
            }
            .bg-green-biofarm {
                background-color: #1A5632;
            }
        </style>
        <!-- jQuery-->
        <script src='<?php echo $this->link('/startbootstrap/vendor/jquery/jquery.min.js');?>'></script>
    </head>
    <body class='bg-green-biofarm' role='document'>

        <div class='container'>

            <!-- Outer Row -->
            <div class='row justify-content-center'>
                <div class='col-xl-10 col-lg-12 col-md-9'>
                    <div class='card o-hidden border-0 shadow-lg my-5'>
                        <div class='card-body p-0'>
                            <!-- Nested Row within Card Body -->
                            <div class='row'>
                                <div class='col-lg-6 d-none d-lg-block bg-login-image'></div>
                                <div class='col-lg-6'>

                                    <?php echo $viewContent; ?>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>



        <!-- Bootstrap core JavaScript-->
        <script src='<?php echo $this->link('/startbootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js');?>'></script>

        <!-- Core plugin JavaScript-->
        <script src='<?php echo $this->link('/startbootstrap/vendor/jquery-easing/jquery.easing.min.js');?>'></script>

        <!-- Custom scripts for all pages-->
        <script src='<?php echo $this->link('/startbootstrap/js/sb-admin-2.min.js');?>'></script>
    </body>
</html>